name: PHP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Run once every week, in order to update external assets.
    - cron: '0 0 * * 1'
    # Run at the birthday of the founder.
    - cron: '30 0 2 11 *'

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    container: srcoder/development-php:php81-fpm

    steps:
      - name: Install NPM
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
          apt install -y nodejs

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build website
        run: make public
        env:
          WEBSITE: ${{ secrets.WEBSITE }}

      - name: Upload artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
          retention-days: 5

  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name != 'pull_request' }}
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        if: ${{ !env.ACT }}
        uses: actions/download-artifact@v2

        with:
          name: public
          path: public

      - name: Deploy
        if: ${{ !env.ACT }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
