name: PHP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    container: srcoder/development-php:php80-fpm

    steps:
      - name: Install GIT LFS
        run: |
          if ! apt satisfy git-lfs &> /dev/null; then apt update -y; fi
          apt install git-lfs -y

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build website
        run: make public
        env:
          WEBSITE: ${{ secrets.WEBSITE }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
          retention-days: 5

  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' }}
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
