name: PHP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    container: srcoder/development-php:php80-fpm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build website
        run: make public

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
          retention-days: 5

  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
