name: PHP

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    container: srcoder/development-php:php81-fpm

    steps:
      - name: Install NPM
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
          apt install -y nodejs

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build website
        run: make public
        env:
          WEBSITE: ${{ secrets.WEBSITE }}

      - name: Upload artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
          retention-days: 5

#      - name: Install Chromium
#        run: apt install chromium chromium-l10n -y
#
#      - name: Lighthouse
#        run: make lighthouse

  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' }}
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        if: ${{ !env.ACT }}
        uses: actions/download-artifact@v2

        with:
          name: public
          path: public

      - name: Deploy
        if: ${{ !env.ACT }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
